### ISSUE TITLE
Ncrit command is incorrect for xfoil 6.99

### ISSUE THREAD

**Issue by ss1870** [usuaero/AirfoilDatabase#10]
Hi there,

I think the command for setting Ncrit is incorrect, at least for my version of xfoil (6.99).

It should just be a single 'N' for both surfaces, and not differentiated between top and bottom surfaces. As it currently stands, no error is thrown, but Ncrit is just not set as requested.

https://github.com/usuaero/AirfoilDatabase/blob/f018674651c1431247cee74b5b24046249713bcf/airfoil_db/airfoil.py#L2129-L2139

Kind regards,

Sam

**Comment by corygoates** [comment]
This is working with my version of Xfoil (6.99 install via apt on Linux Mint). Could you provide more details as to what is going wrong on your end?

**Comment by ss1870** [comment]
Hi Cory,

For reference, I am using the xfoil 6.99 windows executable available at: https://web.mit.edu/drela/Public/web/xfoil/
I would be surprised if the inputs were different between Linux and windows versions, but I have not yet checked the linux version myself. There is also no mention of different Ncrit values for lower/upper surfaces in the windows or linux documentation. From reading the section on 'Transition criterion', I don't think it would physically make sense to specify this amplification factor differently for the upper and lower surfaces.

Here is a screenshot of me attempting to use the commands - 'NT' and 'NB' - that are used by AirfoilDatabase, and then the correct command for my version 'N':
![image](https://github.com/usuaero/AirfoilDatabase/assets/38209284/c7f9728f-c35a-49c9-8ab7-8b6f90f11f3e)

Kind regards,

Sam

**Comment by corygoates** [comment]
Thanks for the extra info. It really doesn't make sense to me either. Here's what my xfoil output looks like:

![ncrit](https://github.com/usuaero/AirfoilDatabase/assets/30323778/b0444eef-05b3-4228-adc7-0ef0c8cbce60)

I don't know why they wouldn't have that in the docs.

I suppose since xfoil will just ignore a bad command, I could set it so AirfoilDatabase will try to put in both commands. Would you be willing to help me test that once I've got it implemented?

**Comment by corygoates** [comment]
Actually, it looks like the Linux version accepts both "N" and "NT/NB" as commands. I'll just update AirfoilDatabase to only use "N". I can't imagine anyone will ever want to specify the critical amplification otherwise, especially if that's not outlined in the docs.

**Comment by corygoates** [comment]
Fixed.

**Comment by ss1870** [comment]
Thanks!

**Comment by corygoates** [comment]
No problem! Thanks for pointing that out.
