### ISSUE TITLE
Bugfix in airfoil.py line 2681

### ISSUE THREAD

**Issue by AlexBdx** [usuaero/AirfoilDatabase#7]
Numpy's default for linspace is 100 elements in the array but you chose to go with arrays of length 30. As a result, an IndexError is thrown when the user defines its own min/max alpha.
This line needs to be edited:

[https://github.com/usuaero/AirfoilDatabase/blob/master/airfoil_db/airfoil.py#L2681](https://github.com/usuaero/AirfoilDatabase/blob/master/airfoil_db/airfoil.py#L2681)

It should read:
```python
alpha = np.linspace(linear_limits[0], linear_limits[1], 30)
```

The array length could also be made another kwarg if that would be useful for users.

I made a new branch and tried to push the changes. However, I do not seem to have the authorization to push. Would it be possible to get added to the list of users able to do so? Thanks!

Alex

**Comment by corygoates** [comment]
Fixed. Sorry for the delay.
